name: proxypool-docker

on:
  workflow_dispatch:

jobs:
  build-push:
    name: Push docker image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: qculug/dockerfiles
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/aarch64
          file: proxypool/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/proxypool:latest
